default_app_config = 'django_po.apps.DjangoPoConfig'
__name__ = 'Django PO'
__author__ = 'Neeraj Kumar'
__version__ = '0.0.1'
__author_email__ = 'sainineeraj1234@gmail.com'
__description__ = 'Export PO file data into files using simple commands'
